function plotTimeSeries(X_elevator, X_aileron, X_rudder, time, plotResults)

    % Create plots
    X_elevatorPlot = [X_elevator(1, :); X_elevator(6, :); X_elevator(2, :); ...
        X_elevator(7, :); X_elevator(3, :); X_elevator(8, :); ....
        euler2quat([X_elevator(9, :); X_elevator(4, :); X_elevator(10, :)]); ...
        zeros(size(X_elevator(1, :))); zeros(size(X_elevator(1, :))); ...
        X_elevator(5, :)];
    X_aileronPlot = [X_aileron(1, :); X_aileron(6, :); X_aileron(2, :); ...
        X_aileron(7, :); X_aileron(3, :); X_aileron(8, :); ....
        euler2quat([X_aileron(9, :); X_aileron(4, :); X_aileron(10, :)]); ...
        zeros(size(X_aileron(1, :))); zeros(size(X_aileron(1, :))); ...
        X_aileron(5, :)];
    X_rudderPlot = [X_rudder(1, :); X_rudder(6, :); X_rudder(2, :); ...
        X_rudder(7, :); X_rudder(3, :); X_rudder(8, :); ....
        euler2quat([X_rudder(9, :); X_rudder(4, :); X_rudder(10, :)]); ...
        zeros(size(X_rudder(1, :))); zeros(size(X_rudder(1, :))); ...
        X_rudder(5, :)];
    
    if plotResults
        
        % Plot results
        plotData(X_elevatorPlot, time)
    end
end